### ISSUE TITLE
erro with test

### ISSUE THREAD

**Issue by moyans** [Canjie-Luo/MORAN_v2#14]
Start val
correct / total: 111 / 4840, 
Test loss: 1.247811, accuray: 0.022934
Traceback (most recent call last):
  File "main.py", line 245, in <module>
    opt.experiment, epoch, i))
  File "/home/train/.pyenv/versions/2.7.13/envs/p2_pytorch0.3/local/lib/python2.7/site-packages/torch/serialization.py", line 135, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/train/.pyenv/versions/2.7.13/envs/p2_pytorch0.3/local/lib/python2.7/site-packages/torch/serialization.py", line 117, in _with_file_like
    return body(f)
  File "/home/train/.pyenv/versions/2.7.13/envs/p2_pytorch0.3/local/lib/python2.7/site-packages/torch/serialization.py", line 135, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/train/.pyenv/versions/2.7.13/envs/p2_pytorch0.3/local/lib/python2.7/site-packages/torch/serialization.py", line 204, in _save
    serialized_storages[key]._write_file(f)
RuntimeError: Unknown error -1
Exception socket.error: error(111, 'Connection refused') in <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7fe887fba190>> ignored

**Comment by Canjie-Luo** [comment]
It seems like a PyTorch Bug. Please ref to [issue#8477](https://github.com/pytorch/pytorch/issues/8477). Do have enough hard-disk space?
