### ISSUE TITLE
run error with multi GPUS

### ISSUE THREAD

**Issue by xiaoyubing** [Canjie-Luo/MORAN_v2#16]
when I run the script:
GPU=0,1,2,3
CUDA_VISIBLE_DEVICES=${GPU} \
python main.py \
        ......
    --ngpu 4
I got an error 'tensors are on different GPUs'.
I can run the training script with a single gpu, but when I want to run it with multi gpus, I got some proplems.
Anybody can help me?Thanks a lot.

This is the full error imformation:

Traceback (most recent call last):
  File "main.py", line 238, in <module>
    acc_tmp = val(test_dataset, criterion)
  File "main.py", line 157, in val
    preds0, preds1 = MORAN(image, length, text, text_rev, test=True)
  File "/home/superpc/miniconda2/envs/pytorch-0.3-py2.7-OCR/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/superpc/miniconda2/envs/pytorch-0.3-py2.7-OCR/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 73, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/superpc/miniconda2/envs/pytorch-0.3-py2.7-OCR/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 83, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/superpc/miniconda2/envs/pytorch-0.3-py2.7-OCR/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
RuntimeError: tensors are on different GPUs

**Comment by Canjie-Luo** [comment]
Multi-GPU training is not support yet, due to the variant lengths of the text in a batch.

**Comment by Mulan337287** [comment]
The variant lengths of text in a batch causes fail in multi-GPUs training, does that means if num_steps is fixed, multi-GPUs training is workable?

**Comment by Canjie-Luo** [comment]
Yes. The code can be developed for multi-GPU training.
