### ISSUE TITLE
训练出问题

### ISSUE THREAD

**Issue by wuxiaolianggit** [Canjie-Luo/MORAN_v2#81]
"See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "main.py", line 243, in <module>
    acc_tmp = val(test_dataset, criterion)
  File "main.py", line 186, in val
    preds = MORAN(image, length, text, text_rev, test=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/wuxl/ocr/MORAN_v2/models/moran.py", line 20, in forward
    preds = self.ASRN(x_rectified, length, text, text_rev, test)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/wuxl/ocr/MORAN_v2/models/asrn_res.py", line 256, in forward
    output = self.attention(rnn, length, text, test)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/wuxl/ocr/MORAN_v2/models/asrn_res.py", line 129, in forward
    probs = Variable(torch.zeros(nB*num_steps, self.num_classes))
TypeError: an integer is required

请问大神这个怎么解决？ @ @am1tyadav @cclauss @

**Comment by cclauss** [comment]
[__input__](https://docs.python.org/3/library/functions.html#input) is a builtin function in both Python 2 and Python 3 so it is not a good idea to have a variable called input.

**Comment by Canjie-Luo** [comment]
您好，line 129这里有非整型参数。
